### ISSUE TITLE
Got "Breakpoint set but not yet bound" on debug start

### ISSUE THREAD

**Issue by sergey-akhalkov** [Microsoft/vscode-chrome-debug-core#293] opened 2018-02-26 14:37 UTC
Hey guys, 

We are maintainers of `vscode-react-native` extension and recently we've got the following issue: https://github.com/Microsoft/vscode-react-native/issues/625#issuecomment-368421380 - for some reason, debugging does not stop on breakpoints on the first start, but it actually works as expected when we are removing and adding breakpoints again.

As I know, previously the following hack has been implemented to avoid such kind of problem, but currently it does not work https://github.com/Microsoft/vscode-react-native/blob/e315e3db8545c6f69dd85e9bb0b17b239e52500b/src/debugger/nodeDebugWrapper.ts#L205

So could you please help us to resolve it or give us right direction/advice?

**Comment by roblourens** [comment] 2018-03-05 19:44
Do you know with what version of vscode-chrome-debug-core it stopped working?

Can you provide a log of a run where this problem is reproduced?

I hope you file an issue next time you have to do a weird hack to work around something :)

**Comment by ruslan-bikkinin** [comment] 2018-03-07 11:16
Hi @roblourens 
I tested it on different version of `vscode` and latest `vscode-chrome-debug-core` version - `3.20.0` and found out that issue is reproducing only on the latest `vscode` version - `1.20.1`, not `1.19.3` or `0.18.1`. Do you have any clues what could be the cause of the issue?

**Comment by roblourens** [comment] 2018-03-07 17:42
You depend on the builtin version of node-debug2 right? I think something changed around when that _attachMode flag is checked. That's the danger of a hack like that.

**Comment by mikes-gh** [comment] 2018-03-09 15:17
I also have issues setting break points using chrome debugger
I am on 1.21
Sometime a grey circle (especially after stating a debug session).
It still goes into debug.
If I remove breakpoint refresh browser and re-add breakpoint it goes red again and still goes into debug.

**Comment by ruslan-bikkinin** [comment] 2018-03-12 08:36
@roblourens yes, we depend on `ms-vscode.node-debug2`.

**Comment by roblourens** [comment] 2018-05-02 23:43
Duplicate of https://github.com/Microsoft/vscode-node-debug2/issues/177

**Closed by roblourens** 2018-05-02 23:43 UTC
